PATHS:
  TRAINDATA_INPUT_PATH: "TrainingData/arcade/arcade_small_invalid_confs_410.csv" # invalid configurations (all stored in .csv file)
  TRAINDATA_OUTPUT_PATH: "TrainingData/arcade/arcade_small_conflicts_410.csv"    # conflicts computed by the solver (also stored in .csv format)
  TRAINDATA_CONSTRAINTS_NAME_PATH: "TrainingData/arcade/arcade_constraints_names.txt" # name of all constraints (must be same order as in the .csv file)
  
  # bigger dataset (48752 invalid configurations)
  # TRAINDATA_INPUT_PATH: "TrainingData/arcade/arcade_invalid_confs_48752.csv" # invalid configurations (all stored in .csv file)
  # TRAINDATA_OUTPUT_PATH: "TrainingData/arcade/arcade_conflicts_48752.csv"    # conflicts computed by the solver (also stored in .csv format)
  # TRAINDATA_CONSTRAINTS_NAME_PATH: "TrainingData/arcade/arcade_constraints_names.txt" # name of all constraints (must be same order as in the .csv file)

  SOLVER_INPUT_PATH: "Solver/Input"     # invalid configurations (each config is a text file)
  SOLVER_OUTPUT_PATH: "Solver/Output"   # conflicts computed by the solver (each conflict is a text file)

  SOLVER_PATH: "Solver/fm_conflict.jar"     # the solver's code (JAR file)
  SOLVER_FM_PATH: "Solver/arcade-game.splx"   # the feature model (SPLX file)

  SOLVER_LOGS_PATH: "Solver/Logs"     # store the logs of the solver (if any)

CLEAR:
  LOGS: true            # clear the logs folder (if any) before running the script
  Solver's input/output: true       # clear the solver's input/output folders (if any) before running the script
  MODELS: false           # clear all trained models from the past
